name: Maven Build

on:
  workflow_call:
    secrets:
      MAVEN_SETTINGS_BASE64:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout reusable workflow repo
        uses: actions/checkout@v4
        with:
          repository: anil-cicd-org/maven-deploy-workflows-master
          ref: main

      - name: Setup Java & Maven
        uses: ./.github/actions/setup-java-maven
        with:
          maven-settings-base64: ${{ secrets.MAVEN_SETTINGS_BASE64 }}

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: mule-application
          path: target/*.jar
