name: Reusable MuleSoft Deployment

on:
   workflow_call:
    secrets:
      MAVEN_SETTINGS_BASE64:
        required: true
    
jobs:
  # ---------------------------
  # Build Job
  # ---------------------------
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
    
    - name: Checkout reusable workflow repo
      uses: actions/checkout@v4
      with:
        repository: anil-cicd-org/maven-deploy-workflows-master
        ref: main
        path: reusable-repo

    - name: Setup Java & Maven
      uses: ./reusable-repo/.github/actions/setup-java-maven
      with:
        maven-settings-base64: ${{ secrets.MAVEN_SETTINGS_BASE64 }}

    - name: Cache Maven packages
      uses: actions/cache@v4
      with:
        path: |
          ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Build with Maven
      run: mvn clean deploy -DskipMunitTests -Pdev

    - name: Upload Artifact for Deployment
      uses: actions/upload-artifact@v4
      with:
        name: mule-application
        path: target/*.jar

# ---------------------------
  # Deployment Job
  # ---------------------------
  deploy: 
    needs: build   
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Checkout reusable workflow repo
      uses: actions/checkout@v4
      with:
        repository: anil-cicd-org/maven-deploy-workflows-master
        ref: main
        path: reusable-repo

    - name: Setup Java & Maven
      uses: ./reusable-repo/.github/actions/setup-java-maven
      with:
        maven-settings-base64: ${{ secrets.MAVEN_SETTINGS_BASE64 }}

    - name: Download Artifact
      uses: actions/download-artifact@v4
      with:
        name: mule-application

    - name: Deploy to CloudHub 2.0
      run: |
        mvn deploy -DskipMunitTests -DmuleDeploy -Pdev

