name: Maven Build

on:
  workflow_call:
    secrets:
      MAVEN_SETTINGS_BASE64:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout reusable workflow repo
        uses: actions/checkout@v4
        with:
          repository: anil-cicd-org/maven-deploy-workflows-master
          ref: main

      - name: Setup Java & Maven
        uses: ./.github/actions/setup-java-maven
        with:
          maven-settings-base64: ${{ secrets.MAVEN_SETTINGS_BASE64 }}

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build & Package
        run: mvn clean package -DskipMunitTests -Pdev # hardcoded to 'dev'

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: mule-application
          path: target/*.jar
