name: Reusable MuleSoft Deployment

on:
   workflow_call:
    secrets:
      MAVEN_SETTINGS_BASE64:
        required: true
      SECRET_VALUE:
        required: true
    inputs:
      environment:
        required: true
        type: string

concurrency:
  group: deploy-${{ inputs.environment }}
  cancel-in-progress: false
    
jobs:
  # ---------------------------
  # Build Job
  # ---------------------------
  app-build:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
    
    - name: Checkout reusable workflow repo
      uses: actions/checkout@v4
      with:
        repository: anil-cicd-org/maven-deploy-workflows-master
        ref: main
        path: reusable-repo

    - name: Show received secrets
      env:
        SECRET_VALUE1: ${{ secrets.SECRET_VALUE }}
      run: |
        if [ -z "$SECRET_VALUE1" ]; then
        echo "SECRET_VALUE is empty"
        else
        echo "SECRET_VALUE length: ${#SECRET_VALUE1}"
        fi
        

#     - name: Setup Java & Maven
#       uses: ./reusable-repo/.github/actions/setup-java-maven
#       with:
#         maven-settings-base64: ${{ secrets.MAVEN_SETTINGS_BASE64 }}

#     - name: Cache Maven packages
#       uses: actions/cache@v4
#       with:
#         path: |
#           ~/.m2/repository
#         key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
#         restore-keys: |
#           ${{ runner.os }}-maven-

#     - name: Build with Maven
#       run: mvn clean deploy -DskipMunitTests -Pdev

#     - name: Upload Artifact for Deployment
#       uses: actions/upload-artifact@v4
#       with:
#         name: mule-application
#         path: target/*.jar

# # ---------------------------
#   # Deployment Job
#   # ---------------------------
#   deploy-dev: 
#     needs: app-build
#     runs-on: ubuntu-latest
#     steps:
#     - name: Checkout Code
#       uses: actions/checkout@v4

#     - name: Checkout reusable workflow repo
#       uses: actions/checkout@v4
#       with:
#         repository: anil-cicd-org/maven-deploy-workflows-master
#         ref: main
#         path: reusable-repo

#     - name: Setup Java & Maven
#       uses: ./reusable-repo/.github/actions/setup-java-maven
#       with:
#         maven-settings-base64: ${{ secrets.MAVEN_SETTINGS_BASE64 }}

#     - name: Download Artifact
#       uses: actions/download-artifact@v4
#       with:
#         name: mule-application

#     - name: Deploy to CloudHub 2.0
#       run: |
#         mvn deploy -DskipMunitTests -DmuleDeploy -Pdev

#   deploy-test: 
#     needs:
#       - app-build
#       - deploy-dev      
#     runs-on: ubuntu-latest
#     environment: 
#       name: test
#     steps:
#     - name: Checkout Code
#       uses: actions/checkout@v4

#     - name: Checkout reusable workflow repo
#       uses: actions/checkout@v4
#       with:
#         repository: anil-cicd-org/maven-deploy-workflows-master
#         ref: main
#         path: reusable-repo

#     - name: Setup Java & Maven
#       uses: ./reusable-repo/.github/actions/setup-java-maven
#       with:
#         maven-settings-base64: ${{ secrets.MAVEN_SETTINGS_BASE64 }}

#     - name: Download Artifact
#       uses: actions/download-artifact@v4
#       with:
#         name: mule-application

#     - name: Deploy to CloudHub 2.0
#       run: |
#         mvn deploy -DskipMunitTests -DmuleDeploy -Ptest

