name: Reusable MuleSoft Deployment

on:
   workflow_call:
    secrets:
      MAVEN_SETTINGS_BASE64:
        required: true
    
jobs:
  # ---------------------------
  # Build Job
  # ---------------------------
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup Java & Maven
      uses: ./reusable-repo/.github/actions/setup-java-maven
      with:
          maven-settings-base64: ${{ secrets.MAVEN_SETTINGS_BASE64 }}

    - name: Cache Maven packages
      uses: actions/cache@v4
      with:
        path: |
          ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Build with Maven
      run: mvn clean deploy -DskipMunitTests -Pdev

    - name: Upload Artifact for Deployment
      uses: actions/upload-artifact@v4
      with:
        name: mule-application
        path: target/*.jar

# ---------------------------
  # Deployment Job
  # ---------------------------
  deploy: 
    needs: build   
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up OpenJDK 11
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Set up Maven
      uses: stCarolas/setup-maven@v4
      with:
        maven-version: '3.9.6'

    - name: Inject Maven settings.xml
      run: |
        mkdir -p ~/.m2
        echo "${{ secrets.MAVEN_SETTINGS_BASE64 }}" | base64 --decode > ~/.m2/settings.xml

    - name: Download Artifact
      uses: actions/download-artifact@v4
      with:
        name: mule-application

    - name: Deploy to CloudHub 2.0
      run: |
        mvn deploy -DskipMunitTests -DmuleDeploy -Pdev

