name: Reusable MuleSoft Deployment

on:
  workflow_call:
    inputs:
      targetEnv:
        required: true
        type: string
    secrets:
      MAVEN_SETTINGS_BASE64:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
      with:
        repository: anil-cicd-org/maven-deploy-workflows-master
        ref: main

    - name: Setup Java & Maven
      uses: ./.github/actions/setup-java-maven

    - name: Cache Maven packages
      uses: actions/cache@v4
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Build & Package
      run: mvn clean package -DskipMunitTests -P${{ inputs.targetEnv }}

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: mule-application
        path: target/*.jar

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment: ${{ inputs.targetEnv }}
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup Java & Maven
      uses: ./.github/actions/setup-java-maven

    - name: Download Artifact
      uses: actions/download-artifact@v4
      with:
        name: mule-application

    - name: Deploy to CloudHub 2.0
      run: mvn deploy -DskipMunitTests -DmuleDeploy -P${{ inputs.targetEnv }}
